### ISSUE TITLE
missing (?) annotations

### ISSUE THREAD

**Issue by soldierofhell** [dineshreddy91/carfusion_to_coco#1]
Hi @dineshreddy91,

Thank you for making your dataset publicly available.
While browsing random photos from visualization script I've noticed that not all instances are annotated. 
Taking for example camshot car_craig2/images_jpg/0_12000.jpg. There are 4 instances here and the two that are closer are not annotated (I've checked that in both bb and gt txt files). Why is that?
![0_12000_kp](https://user-images.githubusercontent.com/45559276/60435780-ad250000-9c0a-11e9-9b8d-2089daff0e8f.png)

**Comment by dineshreddy91** [comment]
Hi @soldierofhell 
Yes we could not label each and every object in the scene and we removed some very large and very small images from labeling. If you are training any network you can detect these vehicles very easily to mask them out for training keypoints.

**Comment by soldierofhell** [comment]
Yes, of course. Just wanted to be sure I haven't lost anything along the way :)
