### ISSUE TITLE
Cannot download Bulter Sequence Part2

### ISSUE THREAD

**Issue by motokimura** [dineshreddy91/carfusion_to_coco#2]
Hi @dineshreddy91 

I requested access to CarFusion dataset via Google Form and received an email with the urls to the dataset.
However, one of the links (Bulter Sequence Part2) does not work.
I tried several times, but got 404 error.

Could you tell me how I can get Bulter Part2 data?
Thank you in advance.

**Comment by dineshreddy91** [comment]
can you use the download_carfusion.py file to download all the data. The link seems to have expired but the data is still at the location. Another option is to use the icons at the Botton of the email and pressing car_butler2.zip

**Comment by motokimura** [comment]
I clicked the icon in the email ant it worked!
(download_carfusion.py did not work for Bulter#2)

Thank you so much for your quick response!
