### ISSUE TITLE
Key points information

### ISSUE THREAD

**Issue by XiongZhongxia** [dineshreddy91/carfusion_to_coco#3]
Hi,  @dineshreddy91. Thanks for your contribution!

I only find 12 rather than 14 points according to the sample images. Another  problem is that which parts (e.g. left headlight， right rear light...) of a vehicle are considered as key points in Carfusion. Could you provide more information for annotated key points？

**Comment by XiongZhongxia** [comment]
Never mind. I found key point names in Occlusion_Net/lib/data_loader/datasets/keypoint.py. 

    NAMES = [
        'Right_Front_wheel',
	'Left_Front_wheel',
	'Right_Back_wheel',
	'Left_Back_wheel',
	'Right_Front_HeadLight',
	'Left_Front_HeadLight',
	'Right_Back_HeadLight',
	'Left_Back_HeadLight',
	'Exhaust',
	'Right_Front_Top',
	'Left_Front_Top',
	'Right_Back_Top',
	'Left_Back_Top',
        'Center'
    ]

I have also checked several annotation files in CarFusion, I'm pretty sure that '**Exhaust' and 'Center' points are not included in GT files.** So actually there are annotations of only 12 points. But why the channel dimension of kp_logits in Occlusion_Net/.../graph_head.py is 14？？

**Comment by dineshreddy91** [comment]
We labelled 14 points with the exhaust and the center. but they were hard to annotate and were giving ambiguous results. We ignore both of these points in most of our evaluations and visualizations and concentrate on the 12 points which are consistent and used across all of our frameworks.  in case of Occlusion_Net/.../graph_head.py we use 14 as a buffer and generally ignore the output for exhaust and the center.
